import React from 'react';
import { expect } from 'chai';
import { mount } from 'enzyme';

import {WeatherTile} from './weatherTile.js';

describe('<WeatherTile />', () => {

	var testData = {
	    'latitude': 47.6062,
	    'longitude': -122.3321,
	    'timezone': 'America/Los_Angeles',
	    'offset': -7,
	    'currently': {
	        'time': 1491585801,
	        'summary': 'Overcast',
	        'icon': 'cloudy',
	        'nearestStormDistance': 1,
	        'nearestStormBearing': 348,
	        'precipIntensity': 0,
	        'precipProbability': 0,
	        'temperature': 52.63,
	        'apparentTemperature': 52.63,
	        'dewPoint': 45.35,
	        'humidity': 0.76,
	        'windSpeed': 6.83,
	        'windBearing': 172,
	        'visibility': 9.49,
	        'cloudCover': 0.94,
	        'pressure': 990.17,
	        'ozone': 391.5
	    },
	    'hourly': {
	        'summary': 'Light rain starting this afternoon, continuing until tomorrow morning, and breezy starting this afternoon, continuing until this evening.',
	        'icon': 'rain',
	        'data': [
	            {
	                'time': 1491584400,
	                'summary': 'Light Rain',
	                'icon': 'rain',
	                'precipIntensity': 0.0162,
	                'precipProbability': 0.59,
	                'precipType': 'rain',
	                'temperature': 52.63,
	                'apparentTemperature': 52.63,
	                'dewPoint': 46.15,
	                'humidity': 0.79,
	                'windSpeed': 5.36,
	                'windBearing': 167,
	                'visibility': 9.2,
	                'cloudCover': 0.98,
	                'pressure': 989.95,
	                'ozone': 392.28
	            },
	            {
	                'time': 1491588000,
	                'summary': 'Mostly Cloudy',
	                'icon': 'partly-cloudy-day',
	                'precipIntensity': 0,
	                'precipProbability': 0,
	                'temperature': 52.77,
	                'apparentTemperature': 52.77,
	                'dewPoint': 44.19,
	                'humidity': 0.73,
	                'windSpeed': 9.21,
	                'windBearing': 176,
	                'visibility': 9.96,
	                'cloudCover': 0.88,
	                'pressure': 990.5,
	                'ozone': 390.29
	            },
	            {
	                'time': 1491591600,
	                'summary': 'Light Rain',
	                'icon': 'rain',
	                'precipIntensity': 0.012,
	                'precipProbability': 0.53,
	                'precipType': 'rain',
	                'temperature': 54.35,
	                'apparentTemperature': 54.35,
	                'dewPoint': 43.84,
	                'humidity': 0.68,
	                'windSpeed': 13.22,
	                'windBearing': 184,
	                'visibility': 9.94,
	                'cloudCover': 1,
	                'pressure': 991.22,
	                'ozone': 389.31
	            },
	            {
	                'time': 1491595200,
	                'summary': 'Light Rain',
	                'icon': 'rain',
	                'precipIntensity': 0.0144,
	                'precipProbability': 0.56,
	                'precipType': 'rain',
	                'temperature': 56.05,
	                'apparentTemperature': 56.05,
	                'dewPoint': 44.91,
	                'humidity': 0.66,
	                'windSpeed': 16.31,
	                'windBearing': 190,
	                'visibility': 9.92,
	                'cloudCover': 1,
	                'pressure': 992.08,
	                'ozone': 388.61
	            },
	            {
	                'time': 1491598800,
	                'summary': 'Light Rain and Breezy',
	                'icon': 'rain',
	                'precipIntensity': 0.0132,
	                'precipProbability': 0.55,
	                'precipType': 'rain',
	                'temperature': 55,
	                'apparentTemperature': 55,
	                'dewPoint': 44.06,
	                'humidity': 0.67,
	                'windSpeed': 19,
	                'windBearing': 191,
	                'visibility': 9.94,
	                'cloudCover': 1,
	                'pressure': 992.91,
	                'ozone': 388.41
	            },
	            {
	                'time': 1491602400,
	                'summary': 'Light Rain and Breezy',
	                'icon': 'rain',
	                'precipIntensity': 0.0128,
	                'precipProbability': 0.54,
	                'precipType': 'rain',
	                'temperature': 55.2,
	                'apparentTemperature': 55.2,
	                'dewPoint': 44.61,
	                'humidity': 0.67,
	                'windSpeed': 20.43,
	                'windBearing': 192,
	                'visibility': 9.94,
	                'cloudCover': 1,
	                'pressure': 993.56,
	                'ozone': 388.84
	            },
	            {
	                'time': 1491606000,
	                'summary': 'Light Rain and Breezy',
	                'icon': 'rain',
	                'precipIntensity': 0.0155,
	                'precipProbability': 0.57,
	                'precipType': 'rain',
	                'temperature': 53.58,
	                'apparentTemperature': 53.58,
	                'dewPoint': 43.27,
	                'humidity': 0.68,
	                'windSpeed': 22.08,
	                'windBearing': 192,
	                'visibility': 9.93,
	                'cloudCover': 1,
	                'pressure': 994.17,
	                'ozone': 389.77
	            }
	        ]
	    },
	    'daily': {
	        'summary': 'Light rain throughout the week, with temperatures peaking at 59°F on Sunday.',
	        'icon': 'rain',
	        'data': [
	            {
	                'time': 1491548400,
	                'summary': 'Light rain in the morning and afternoon and breezy starting in the afternoon, continuing until evening.',
	                'icon': 'rain',
	                'sunriseTime': 1491572182,
	                'sunsetTime': 1491619709,
	                'moonPhase': 0.39,
	                'precipIntensity': 0.017,
	                'precipIntensityMax': 0.0448,
	                'precipIntensityMaxTime': 1491559200,
	                'precipProbability': 0.71,
	                'precipType': 'rain',
	                'temperatureMin': 45.58,
	                'temperatureMinTime': 1491631200,
	                'temperatureMax': 56.05,
	                'temperatureMaxTime': 1491595200,
	                'apparentTemperatureMin': 39.06,
	                'apparentTemperatureMinTime': 1491631200,
	                'apparentTemperatureMax': 56.05,
	                'apparentTemperatureMaxTime': 1491595200,
	                'dewPoint': 44.37,
	                'humidity': 0.8,
	                'windSpeed': 8.45,
	                'windBearing': 192,
	                'visibility': 10,
	                'cloudCover': 0.9,
	                'pressure': 993.09,
	                'ozone': 387.09
	            },
	            {
	                'time': 1491634800,
	                'summary': 'Drizzle in the morning and afternoon.',
	                'icon': 'rain',
	                'sunriseTime': 1491658463,
	                'sunsetTime': 1491706194,
	                'moonPhase': 0.43,
	                'precipIntensity': 0.0052,
	                'precipIntensityMax': 0.0135,
	                'precipIntensityMaxTime': 1491642000,
	                'precipProbability': 0.55,
	                'precipType': 'rain',
	                'temperatureMin': 43.8,
	                'temperatureMinTime': 1491660000,
	                'temperatureMax': 54.62,
	                'temperatureMaxTime': 1491692400,
	                'apparentTemperatureMin': 37.34,
	                'apparentTemperatureMinTime': 1491660000,
	                'apparentTemperatureMax': 54.62,
	                'apparentTemperatureMaxTime': 1491692400,
	                'dewPoint': 39.64,
	                'humidity': 0.75,
	                'windSpeed': 11.56,
	                'windBearing': 206,
	                'visibility': 9.83,
	                'cloudCover': 0.82,
	                'pressure': 1011.25,
	                'ozone': 399.7
	            },
	            {
	                'time': 1491721200,
	                'summary': 'Light rain overnight.',
	                'icon': 'rain',
	                'sunriseTime': 1491744745,
	                'sunsetTime': 1491792678,
	                'moonPhase': 0.46,
	                'precipIntensity': 0.001,
	                'precipIntensityMax': 0.003,
	                'precipIntensityMaxTime': 1491728400,
	                'precipProbability': 0.1,
	                'precipType': 'rain',
	                'temperatureMin': 39.17,
	                'temperatureMinTime': 1491739200,
	                'temperatureMax': 59.08,
	                'temperatureMaxTime': 1491778800,
	                'apparentTemperatureMin': 34.71,
	                'apparentTemperatureMinTime': 1491739200,
	                'apparentTemperatureMax': 59.08,
	                'apparentTemperatureMaxTime': 1491778800,
	                'dewPoint': 36.88,
	                'humidity': 0.68,
	                'windSpeed': 5.25,
	                'windBearing': 173,
	                'visibility': 9.97,
	                'cloudCover': 0.63,
	                'pressure': 1018.12,
	                'ozone': 395
	            },
	            {
	                'time': 1491807600,
	                'summary': 'Light rain in the morning and afternoon.',
	                'icon': 'rain',
	                'sunriseTime': 1491831028,
	                'sunsetTime': 1491879163,
	                'moonPhase': 0.49,
	                'precipIntensity': 0.0159,
	                'precipIntensityMax': 0.0349,
	                'precipIntensityMaxTime': 1491825600,
	                'precipProbability': 0.68,
	                'precipType': 'rain',
	                'temperatureMin': 42.4,
	                'temperatureMinTime': 1491829200,
	                'temperatureMax': 52.35,
	                'temperatureMaxTime': 1491865200,
	                'apparentTemperatureMin': 38.3,
	                'apparentTemperatureMinTime': 1491829200,
	                'apparentTemperatureMax': 52.35,
	                'apparentTemperatureMaxTime': 1491865200,
	                'dewPoint': 41.86,
	                'humidity': 0.82,
	                'windSpeed': 5.94,
	                'windBearing': 206,
	                'visibility': 10,
	                'cloudCover': 0.93,
	                'pressure': 1016.97,
	                'ozone': 416.08
	            },
	            {
	                'time': 1491894000,
	                'summary': 'Mostly cloudy throughout the day.',
	                'icon': 'partly-cloudy-day',
	                'sunriseTime': 1491917312,
	                'sunsetTime': 1491965648,
	                'moonPhase': 0.52,
	                'precipIntensity': 0.0018,
	                'precipIntensityMax': 0.0111,
	                'precipIntensityMaxTime': 1491894000,
	                'precipProbability': 0.52,
	                'precipType': 'rain',
	                'temperatureMin': 41.27,
	                'temperatureMinTime': 1491919200,
	                'temperatureMax': 55.34,
	                'temperatureMaxTime': 1491955200,
	                'apparentTemperatureMin': 38.34,
	                'apparentTemperatureMinTime': 1491908400,
	                'apparentTemperatureMax': 55.34,
	                'apparentTemperatureMaxTime': 1491955200,
	                'dewPoint': 41.5,
	                'humidity': 0.79,
	                'windSpeed': 2.3,
	                'windBearing': 41,
	                'cloudCover': 0.61,
	                'pressure': 1020.33,
	                'ozone': 392.15
	            },
	            {
	                'time': 1491980400,
	                'summary': 'Light rain until evening, starting again overnight.',
	                'icon': 'rain',
	                'sunriseTime': 1492003596,
	                'sunsetTime': 1492052133,
	                'moonPhase': 0.55,
	                'precipIntensity': 0.0218,
	                'precipIntensityMax': 0.05,
	                'precipIntensityMaxTime': 1492009200,
	                'precipProbability': 0.72,
	                'precipType': 'rain',
	                'temperatureMin': 43.2,
	                'temperatureMinTime': 1492009200,
	                'temperatureMax': 55.54,
	                'temperatureMaxTime': 1492048800,
	                'apparentTemperatureMin': 36.86,
	                'apparentTemperatureMinTime': 1492005600,
	                'apparentTemperatureMax': 55.54,
	                'apparentTemperatureMaxTime': 1492048800,
	                'dewPoint': 45.03,
	                'humidity': 0.86,
	                'windSpeed': 4.65,
	                'windBearing': 357,
	                'cloudCover': 0.91,
	                'pressure': 1008.53,
	                'ozone': 399.63
	            },
	            {
	                'time': 1492066800,
	                'summary': 'Rain until evening.',
	                'icon': 'rain',
	                'sunriseTime': 1492089881,
	                'sunsetTime': 1492138617,
	                'moonPhase': 0.58,
	                'precipIntensity': 0.0205,
	                'precipIntensityMax': 0.0579,
	                'precipIntensityMaxTime': 1492081200,
	                'precipProbability': 0.74,
	                'precipType': 'rain',
	                'temperatureMin': 44.61,
	                'temperatureMinTime': 1492095600,
	                'temperatureMax': 56.16,
	                'temperatureMaxTime': 1492128000,
	                'apparentTemperatureMin': 41.17,
	                'apparentTemperatureMinTime': 1492092000,
	                'apparentTemperatureMax': 56.16,
	                'apparentTemperatureMaxTime': 1492128000,
	                'dewPoint': 46.31,
	                'humidity': 0.86,
	                'windSpeed': 7.8,
	                'windBearing': 197,
	                'cloudCover': 0.64,
	                'pressure': 1006.11,
	                'ozone': 416.35
	            }
	        ]
	    },
	};

	it('should not be null', function() {
    	const tile = mount(<WeatherTile>{testData}</WeatherTile>);
    	expect(tile).to.not.be.empty;
  	});
});